### PR TITLE
AmazonPay, MyAirtelUPI & TrueCallerUPI has been added

### PR DESCRIPTION
**Pull request by paritoshpandey966**
I have tested these 3 (AmazonPay, MyAirtelUPI & TrueCallerUPI) and seems working just fine.

### CODE REVIEW

**Review by samarthagarwal — COMMENTED** [review]
Are you sure the response from these apps is still parseable using `FlutterUpiResponse` class? Is the response string in the same format for all these apps?

**Comment by paritoshpandey966** [comment]
responses are as follow :

Paytm =
txnId=PTM2b06a17a14a7489da278ce1b42951386&responseCode=0&ApprovalRefNo=913946497123&Status=SUCCESS&txnRef=23

GooglePay
txnId=HDFbf2b3c3f6e5e4204998ed7a32627a717&responseCode=S&Status=SUCCESS&txnRef=73

PhonePe
txnId=YBL9e16dbf2093b42eebd9b2e1e68d0ea61&txnRef=96&Status=Failed&responseCode=01

MiPay
txnId=&txnRef=29&responseCode=&Status=SUBMITTED

AmazonPay
txnId=GbrjjZnqw59jrnGKHq9wtFcZRuj7py7jxux&responseCode=U16&txnRef=45&status=FAILURE

TruecallerUPI
txnId=null&responseCode=U16&Status=failure&txnRef=37&message=You have exceeded your transaction limit. Please try again later

as we can see only AmazonPay's status parameter has little change which is starting with small "s" instead of "S".

MyAirtelUPI is not returning such response yet, it might be because I've exceeded my transaction limit. as of now you can remove the MyAirtelUPI. I will test it and update it soon.

**Comment by samarthagarwal** [comment]
For AmazonPay, I will update the code to handle both `status` and `Status`.

**Comment by samarthagarwal** [comment]
Were you able to test with the MyAirtelUPI app?

**Comment by samarthagarwal** [comment]
Fixed all and merged. Thanks for your contribution.

**Pull request merged**
