### PR TITLE
PHONEPE and MiPay added

### PR DESCRIPTION
**Pull request by paritoshpandey966**
every app which is using UPI SDK we can add them

### CODE REVIEW

**Review by samarthagarwal — COMMENTED** [review]
Hi. Have you tested the plugin with the two apps - Mi Pay and PhonePe?

**Comment by paritoshpandey966** [comment]
yes I did, and they work like a charm

**Comment by paritoshpandey966** [comment]
I'll soon add amazon pay too

**Comment by samarthagarwal** [comment]
Please do and ensure that you test thoroughly. Obviously, I can't test with all the apps. Thanks for your contribution.

**Pull request merged**
